# Generated by Django 4.2.3 on 2023-09-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_email_verified_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chatbots_available',
            field=models.IntegerField(default=3, verbose_name='chatbots_available'),
        ),
    ]
