# Generated by Django 4.2.3 on 2023-10-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_chatbots_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='chatbot_character_limit',
            field=models.IntegerField(default=400000),
        ),
    ]
