# Generated by Django 4.2.3 on 2023-10-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_chatbot_character_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='chatbot_character_limit',
            field=models.IntegerField(default=1000000),
        ),
    ]
