# Generated by Django 4.2.3 on 2023-09-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartchat',
            name='name',
            field=models.CharField(default='Chat', max_length=50),
        ),
    ]
