# Generated by Django 4.2.3 on 2023-10-05 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_smartchat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartchat',
            name='character_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='smartchat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to=settings.AUTH_USER_MODEL),
        ),
    ]
