# Generated by Django 4.2.3 on 2023-10-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chatfile_created_smartchat_character_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatfile',
            name='character_length',
            field=models.IntegerField(default=0),
        ),
    ]
