# Generated by Django 4.2.3 on 2023-10-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_chatfile_character_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatfile',
            name='file_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
