# Generated by Django 4.2.3 on 2023-10-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_smartchat_updated_chattext'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattext',
            name='is_question',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='chattext',
            name='question',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=1000),
        ),
    ]
