# Generated by Django 4.2.3 on 2023-10-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_chattext_is_question_alter_chattext_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chattext',
            name='question',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1000),
        ),
    ]
