# Generated by Django 4.2.3 on 2023-10-17 01:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import chats.models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0008_alter_chattext_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('url_html_response', models.FileField(upload_to=chats.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['html'])])),
                ('url_text', models.TextField(max_length=500000)),
                ('character_length', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='chats.smartchat')),
            ],
        ),
    ]
