# Generated by Django 4.2.3 on 2023-10-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0009_chaturl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaturl',
            name='url_html_response',
        ),
    ]
